import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import time
from tqdm import tqdm # 1. Import tqdm

def sigmoid(x):
    """Sigmoid activation function (works on arrays)."""
    return 1 / (1 + np.exp(-x))

def parse_weights_file(filepath):
    """Parses the weights file generated by the C program."""
    epochs_data = {}
    if not os.path.exists(filepath):
        return None
    with open(filepath, 'r') as f:
        epoch = -1
        for line in f:
            parts = line.strip().split(':')
            if parts[0] == 'EPOCH':
                epoch = int(parts[1])
                epochs_data[epoch] = []
            elif parts[0] == 'LAYER':
                epochs_data[epoch].append([])
            elif parts[0] == 'NEURON':
                weights_and_bias = [float(p) for p in parts[2:]]
                weights = np.array(weights_and_bias[:-1])
                bias = weights_and_bias[-1]
                epochs_data[epoch][-1].append({'weights': weights, 'bias': bias})
    return epochs_data

def predict_mlp_vectorized(all_points, epoch_weights):
    """Performs a forward pass for an entire batch of points at once using matrix multiplication."""
    inputs = all_points.T
    for layer_weights in epoch_weights:
        W = np.array([neuron['weights'] for neuron in layer_weights])
        b = np.array([neuron['bias'] for neuron in layer_weights]).reshape(-1, 1)
        activation = W @ inputs + b
        inputs = sigmoid(activation)
    return np.argmax(inputs, axis=0)

def generate_4d_frames():
    """Main function to generate a 4x4 pairs plot for each epoch and save as an image."""
    if not os.path.exists('frames_4d'):
        os.makedirs('frames_4d')

    print("Parsing 4D weights file...")
    epochs_data = parse_weights_file('mlp_weights_4d.txt')
    
    if not epochs_data:
        print("Error: mlp_weights_4d.txt not found.")
        print("Please run the C program first to generate the weights file.")
        return

    print("Loading Iris data...")
    feature_names = ['Sepal.Length', 'Sep.Width', 'Petal.Length', 'Petal.Width']
    species_list = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
    
    iris_df = pd.read_csv('iris.data', header=None, names=feature_names + ['Species'])
    X = iris_df[feature_names].values
    species_map = {species: i for i, species in enumerate(species_list)}
    y = iris_df['Species'].map(species_map).values
    
    feature_means = X.mean(axis=0)

    total_start_time = time.time()
    
    # 2. Wrap the main loop with tqdm()
    print("Generating frames...")
    for epoch, weights in tqdm(epochs_data.items(), desc="Generating Frames"):
        fig, axes = plt.subplots(4, 4, figsize=(15, 15))
        fig.suptitle(f'MLP Decision Boundary Slices - Epoch: {epoch}', fontsize=20)

        for i in range(4):
            for j in range(4):
                ax = axes[i, j]
                if i == j:
                    sns.kdeplot(data=iris_df, x=feature_names[j], hue='Species', fill=True, ax=ax, legend=False)
                else:
                    x_min, x_max = X[:, j].min() - 0.5, X[:, j].max() + 0.5
                    y_min, y_max = X[:, i].min() - 0.5, X[:, i].max() + 0.5
                    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.05),
                                         np.arange(y_min, y_max, 0.05))
                    
                    mesh_points = np.full((xx.ravel().shape[0], 4), feature_means)
                    mesh_points[:, j] = xx.ravel()
                    mesh_points[:, i] = yy.ravel()
                    
                    Z = predict_mlp_vectorized(mesh_points, weights)
                    Z = Z.reshape(xx.shape)
                    
                    ax.contourf(xx, yy, Z, alpha=0.3, cmap=plt.cm.viridis, levels=2)
                    ax.scatter(X[:, j], X[:, i], c=y, cmap=plt.cm.viridis, edgecolors='k')

                if i == 3: ax.set_xlabel(feature_names[j])
                if j == 0: ax.set_ylabel(feature_names[i])
                if i < 3: ax.set_xticklabels([])
                if j > 0: ax.set_yticklabels([])

        plt.tight_layout(rect=[0, 0.03, 1, 0.96])
        plt.savefig(f'frames_4d/frame_{epoch:04d}.png')
        plt.close(fig)
        
        # 3. Remove the old print statement from inside the loop
        # print(f"Generated frame for Epoch {epoch} in {frame_time:.2f} seconds.")

    total_time = time.time() - total_start_time
    print(f"\nAll {len(epochs_data)} frames generated successfully in {total_time:.2f} seconds.")

if __name__ == '__main__':
    generate_4d_frames()