import pandas as pd
import matplotlib.pyplot as plt

# Read the data generated by the C program
try:
    df = pd.read_csv("results.csv")
except FileNotFoundError:
    print("Error: results.csv not found. Please run the C program first.")
    exit()

# Create a plot
plt.style.use('seaborn-v0_8-whitegrid') # Sets a nice plot style
fig, ax = plt.subplots(figsize=(12, 8))

# Plot each training session's accuracy over epochs
for column in df.columns[1:]:  # Skip the 'Epoch' column
    ax.plot(df['Epoch'], df[column], label=column, lw=2.5)

# Add titles and labels for clarity
ax.set_title('Perceptron Training Accuracy Over Time (Step Function)', fontsize=16)
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Test Accuracy (%)', fontsize=12)
ax.legend(title='Training Scenario', fontsize=10)
ax.grid(True)
plt.ylim(0, 105) # Set y-axis limits from 0 to 105%

# Save the plot to a file and show it
plt.savefig("perceptron_accuracy_plot.png")
print("Plot saved to perceptron_accuracy_plot.png")
plt.show()